"""empty message

Revision ID: 0092b2fe6bdf
Revises: 150bd0246747
Create Date: 2018-05-17 10:55:03.821240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0092b2fe6bdf'
down_revision = '150bd0246747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.Column('answer', sa.String(length=1), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['dbqrest.questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dbqrest'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('choices', schema='dbqrest')
    # ### end Alembic commands ###
