"""empty message

Revision ID: d457b52f6593
Revises: e839d2256e85
Create Date: 2018-05-17 11:03:25.304872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd457b52f6593'
down_revision = 'e839d2256e85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('choices_question_id_fkey', 'choices', type_='foreignkey')
    op.create_foreign_key(None, 'choices', 'questions', ['question_id'], ['id'], source_schema='dbqrest', referent_schema='dbqrest')
    op.alter_column('questions', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('questions', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('questions', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'choices', schema='dbqrest', type_='foreignkey')
    op.create_foreign_key('choices_question_id_fkey', 'choices', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###
