"""empty message

Revision ID: e839d2256e85
Revises: 0092b2fe6bdf
Create Date: 2018-05-17 10:59:47.885066

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e839d2256e85'
down_revision = '0092b2fe6bdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('choices_question_id_fkey', 'choices', type_='foreignkey')
    op.create_foreign_key(None, 'choices', 'questions', ['question_id'], ['id'], source_schema='dbqrest', referent_schema='dbqrest')
    op.alter_column('questions', 'creation_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'creation_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'choices', schema='dbqrest', type_='foreignkey')
    op.create_foreign_key('choices_question_id_fkey', 'choices', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###
